#
##################################################################
##                        Default类型参数                        ##
##################################################################
#
#物品名称 Name [Type:String] (支持随机)
#
#物品材质 ID [Type:String] (支持随机)
# 格式-1:
# - 276
# 格式-2: 267
#
#物品耐久 Durability [Type:String] (支持随机)
# 格式-1: 20    原版耐久，"20" 相当于 "该物品耐久只剩(该材质最大耐久-20)"
# 格式-2: <20   反算耐久，"<20" 效果是 "该物品耐久只剩20"
# 格式-3: 20%   百分比耐久，与耐久条相同
# 也可以在ID节点下编写->
# ID:
# - 276:Durability格式
#
#物品数量 Amount [Type:String] (支持随机)
#
#物品描述 Lore [Type:List] (支持随机)
# 格式:
# - "..."
#
#Enchant列表 EnchantList [Type:List] (支持随机)
# 格式:
# - "Enchant名称:Level"
# 参考WIKI: https://minecraft.fandom.com/zh/wiki/%E9%99%84%E9%AD%94
# 参考API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#
#隐藏选项 ItemFlagList [Type:List]
# 描述: 用于隐藏属性、Enchant、无限耐久、药水效果、染色等信息
# 格式:
# - "HIDE_ENCHANTS"
# - "HIDE_ATTRIBUTES"
# - "HIDE_UNBREAKABLE"
# - "HIDE_POTION_EFFECTS"
# 参考API: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
#
#物品染色 NmColor [Type:String] (支持随机)
# 描述: 可以对该物品染色 (仅限皮革防具) ，需要用十六进制AttrColor码 (不需要带#)
# 格式: "000000"
#
#物品属性 Attributes [Type:List] (支持随机)
# 格式:
# - "属性名:数字:模式:生效位置"    # 生效当前位置, 高版本推荐使用
# - "属性名:数字:模式"           # 生效所有位置
# 属性名:
#   GENERIC_MAX_HEALTH               最大生命值
#   GENERIC_FOLLOW_RANGE             生物追踪范围
#   GENERIC_KNOCKBACK_RESISTANCE     抗擊退效果
#   GENERIC_MOVEMENT_SPEED           移动速度
#   GENERIC_FLYING_SPEED             飞行速度
#   GENERIC_ATTACK_DAMAGE            攻击伤害
#   GENERIC_ATTACK_KNOCKBACK         击退力度
#   GENERIC_ATTACK_SPEED             攻击速度
#   GENERIC_ARMOR                    盔甲防御点数
#   GENERIC_ARMOR_TOUGHNESS          盔甲韧性
#   GENERIC_LUCK                     幸运度 (例如原版的当打开箱子、运输矿车，钓鱼和杀怪)
#   HORSE_JUMP_STRENGTH              马的弹跳力(只对马铠生效)
#   ZOMBIE_SPAWN_REINFORCEMENTS      僵尸召唤系数(未测试)
# 模式:
#   0   ADD_NUMBER          属性增量    该模式直接在基值上进行加减法操作
#   1   ADD_SCALAR          倍率增量    该模式将在Operation 0之后执行，并直接在属性值的作用倍率上进行加减法操作，也就是将当前的属性值进行倍率上的修改，而基础倍率为×1倍 (即不做改动)
#   2   MULTIPLY_SCALAR_1   最终倍乘    该模式将会在其他所有修饰 (包括其他的Operation 2修饰) 完成后，在最终倍率上执行加减法操作，并执行最终的倍乘。基础倍率同样为×1倍
# 生效位置: 不填写生效位置则生效在所有部位上
#   HAND      主
#   OFF_HAND  副
#   HEAD      头
#   CHEST     身
#   LEGS      腿
#   FEET      脚
# 参考WIKI: https://minecraft.fandom.com/zh/wiki/%E5%B1%9E%E6%80%A7?variant=zh-cn
# 参考API:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/package-summary.html
#
#自定义材质ID CustomModelData: 1000
#
#药水系统 Potion [Type:Map-?] (部分随机)
# 说明: 药水类型/duration/amplifier支持随机, ambient/particles/icon默认值为ture
#      默认和自定义我觉得没有同时存在的必要, 所以是二选一, 药水效果填错只会不生效
# 格式-1:       默认药水参数
#   Potion: 药水类型
#   Potion: <s:JUMP:ABSORPTION>
# 格式-2:       自定义药水
#   Potion:
#     药水类型:
#       持续时间(duration): 20=1秒
#       效果Level(amplifier): 1
#       氛围(ambient): true
#       粒子特效(particles): true
#       是否显示图标(icon): true
#   Potion:
#     <s:SPEED:SLOW>:
#       duration: <c:20 * <i:10_20>>
#       amplifier: <i:1_2>
#
# 参考API: https://bukkit.windit.net/javadoc/org/bukkit/potion/PotionEffectType.html
#
#物品标签 NBT [Type:Map-?] (支持随机)
# 描述: 自由的将NBT节点下的配置信息设置到物品NBT中，可输入/si nbt查看
#
#清除属性 ClearAttribute [Type:Boolean]
# 描述: 让物品失去原有的默认属性 (代码实现为: ItemFlag.HIDE_ATTRIBUTE + Attributes.GENERIC_ATTACK_DAMAGE:0:0)
#
#保护标签 ProtectNBT [Type:List]
# 描述: 自动更新时保护以下NBT不被更改，可输入/si nbt查看
# 格式:
# - "Enchantments" 保护Enchant词条不被自动更新
# - "!protect.data" 解除在全局保护[Config.yml]中的词条
#
#局部随机 Random [Type:Map-?]
# 描述: 设置物品的局部随机变量
# 格式: 与RandomString文件夹下的格式一样
#
#自动更新 Update [Type:Boolean]
# 描述: 会自动更新该物品 (注意，随机文本除了<l:>以外也会重新生成)
#

Default-1:
  Name: <l:DefaultPrefix> <l:DefaultName> <l:<l:Quality>NmColor><l:Quality>
  ID: <l:<l:Occupation>ID>
  Lore:
    - '&6QualityLevel: <l:<l:Quality>NmColor><l:Quality>'
    - '<b:<l:Quality>:Excellent:Epic>&6LimitOccupation: <l:Occupation>'
    - '&6ItemType: MainWeapon'
    - '&6LimitLevel: <c:int 10 * <s:<l:Quality>Base>> Level'
    - '&cAttack: +<l:Attack>'
    - '<l:ATK1-10>'
    - '<l:ATK2-10>'
    - '<l:ATK3-10>'
    - '<l:Texture>'
    - '<s:<l:Quality>GemSlot>'
    #   - '&7Durability: <c:int <r:300_350> * <s:<l:Quality>Base>>/<c:int 400 * <s:<l:Quality>Base>>'
    - '&7Durability: <c:int <d:0.6_0.9> * <l:Durability>>/<l:Durability>'
    - '<b:<l:Quality>:Epic>&cBound'
    - '&aExpiryTime: <t:10m>'
    #   - '&aExpiryTime: <t:600>'
    - '<b:<l:Quality>:Excellent:Epic>                                    '
    - '<b:<l:Quality>:Excellent:Epic><s:DefaultLore>'
  EnchantList:
    - <s:<l:Occupation>Enchant>
  ClearAttribute: true
  Random:
    Attack: <c:20 * <s:<l:Quality>Base>>
    Durability: <c:int <r:350_400> * <s:<l:Quality>Base>>
  NBT:
    SX-Attribute.Attribute:
      - 'Entry 1'
      - 'Entry 2'
      - 'Entry 3'
      - 'SX-Attribute reserved attribute interface'
      - 'If you need to use random, you need to learn advanced random.'
  ProtectNBT: #PROTECT ENCHANT FROM BEING UPDATED
    - "Enchantments"
  Update: true

Default-2:
  Name: '&cLight Feather Boots'
  ID: 301
  Lore:
    - '&6ItemType: Boots'
    - '&cMaxHP: +2000'
    - '&dSpeed: +50%'
    - '&6LimitLevel: <r:50_100>级'
    - '&r'
    - '&8Speed II'
    - '&cSupport single automatic update-(AutoUpdate)'
    - '&cSupport Single Close Clear Labels'
    - '&r'
    - '&eSalePrice: 250'
  EnchantList:
    - DURABILITY:1
  ItemFlagList:
    - HIDE_ENCHANTS
    - HIDE_UNBREAKABLE
  Unbreakable: true
  NmColor: <s:NmColor>
  Random:
    NmColor:
      - 'ffffff'
      - '000000'
  Update: true

Default-3:
  Name: '&c&lRandomStringDescription'
  # Set durability to 0
  ID: 359:<0
  Lore:
    - ''
    - '&4&l!!! The following content is mainly based on configuration files !!!'
    - ''
    - "&e&l'&c&l<>&e&l' Non-Substitute Variables Required '&c&l\$&e&l' Escape"
    - '&7Format: \$<1:Content> 或 <Content>'
    - '&7ForExample: \$<s:DefaultPrefix> 或 <DefaultPrefix>'
    - ''
    - '&e&lRandomType:'
    - '&cb   - &7WholeLineJudgment&r [<b:Match:String1:String2:String3:String4>] This line was deleted because no matching word is the same as the matching name'
    - '&cb   - &7WholeLineJudgment&r [<b:<l:Quality>:Epic:Excellent:Ordinary>]'
    - '&ct   - &7TimeFormat&r [<t:1Y1M1D1h1m1s>]'
    - '&cc   - &7Calculator&r [<c:((2*3) + 2) * 1.4>] [<c:int ((2*3) + 2) * 1.4>]'
    - '&cl   - &7LockRandom&r [<l:Quality>] [<l:EASY#AAA:BBB:CCC>]'
    - '&cs   - &7NormalRandom&r [<s:<s:Quality>NmColor>♦&r] [<s:AAA:BBB:CCC>]'
    - '&cd   - &7DecimalRandom&r [<d:2.3_6>]'
    - '&ci&7/&cr - &7IntegerRandom&r [<i:1_7>]'
    - '&cu   - &7UUIDRandom&r [<u:random>]'
    - '&cj   - &7ScriptProcessing&r [<j:Default.itemScript#QAQ,QWQ,???,!!!>]'
    - ''
    - "&eLocal Variables call Global Variables ~"
    - "&c ~ &7 represents &4null&7 in yml"
    - '&7Override Global Result -> <s:DefaultPrefix>'
    - '&7Global and Local mixed Result -> <s:DefaultLore>'
    - ''
    - 'Variables that do not exist delete the row: <s:DoesNotExist>'
    - '&r↑here s a line that s been eaten'
  Random:
    DefaultPrefix: "Prefix"
    DefaultLore:
      # 33% probability random to Lore, 66% probability random to global variable
      - 1: "Lore"
      - 2: ~

Default-4:
  Type: Import
  Item:
    ==: org.bukkit.inventory.ItemStack
    type: APPLE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7Import type of apple
      lore:
        - §7An item of type Import
        - ''
        - §cHow to save this type of item?§7
        - ''
        - §7/sx save <ItemID> Import
        - ''
        - §cIt does not support automatic updates§7

Default-5:
  Name: '&bSlow Sword'
  # YML syntax-set the anchor point to be valid only in the current file and what else is Google
  ID: &def5-ID
    - 268
    - 272
    - 283
    - 267
    - 276
  # Set durability to maximum * 20%
  Durability: 20%
  Lore:
    - '&7Use Attributes to set the original attack speed'
    - ''
    - "&c'GENERIC_ATTACK_SPEED:-1:2:HAND' - Tool will not lift"
  Type: Default
  Update: true
  Attributes:
    - "GENERIC_ATTACK_SPEED:-0.7:1:HAND"
    # - "GENERIC_ATTACK_SPEED:-1:2:HAND"

Default-6:
  Name: "&dTickle Sword"
  # YML Syntax-Reference anchor is valid only within the current file
  ID: *def5-ID
  # Set Endurance to a maximum of -30
  Durability: 30
  Attributes:
    - "GENERIC_ATTACK_DAMAGE:-0.99:2:HAND"

Default-7:
  ID: <l:ID#POTION:SPLASH_POTION:LINGERING_POTION>
  Lore: [ "&cAt present, the potion has only implemented versions 1.11.1 and above." ]
  #  Potion: <s:WATER:POTION:JUMP> DoNotUseThisModelAgain
  Potion:
    ABSORPTION: &PotionData
      duration: <c:int 20 * <i:1_10> * <s:<l:ID>>>
      amplifier: <i:1_3>
      ambient: true
      particles: true
      icon: true
    <s:NIGHT_VISION:BLINDNESS>: *PotionData
    <s:SPEED:SLOW>: *PotionData
    <s:INVISIBILITY:GLOWING:???>: *PotionData
  Random:
    POTION: 1
    SPLASH_POTION: 1
    LINGERING_POTION: 4
  Update: true

Default-8:
  ID: 419
  EnchantList:
    # Binding Curse does not take effect on horses
    - BINDING_CURSE:1
  Attributes:
    # It is known that 1.17 versions of horses can obtain attributes from horse armor, versions 1.12.2 and below cannot be used, and other versions have not been tested.
    - "HORSE_JUMP_STRENGTH:2:0:CHEST"
    - "GENERIC_MOVEMENT_SPEED:0.5:1:CHEST"

#Default-9: Default-1
Default-9:
  Name: '&9Items that can be replaced'
  ID: '350'
  Lore:
    - ''
    - '&7If you want to replace this item with Default-1'
    - "&7Please use: 'Default-9: Default-1'"
    - ''
    - '&cUpdate for target (Default-1) must be turned on to replace'
    - '&4&lSubstitution is not retroactive'

# Is a Ordinary SX item, yml shorthand
# A non-existent ID will prevent the item from being give out, but it will not report an error.
Default-10.ID: 'Non-existent items'

# Items prefixed with "NoLoad" will not be loaded
NoLoad_Item:
  ID: 1
  Name: "Items that will not be loaded"
